# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13DtfMZWW5tVjHVjQZsG0K3J5zNZrg79O
"""

a = int(input())
b = int(input())
if(a < b):
  for i in range(a, b + 1, 1):
      print(i)
else:
  for i in range(a, b - 1, -1):
      print(i)