# -*- coding: utf-8 -*-
"""test2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/133KE2Ucq-5uM62nFJL_sh_jzx1Z_6KVJ
"""

a = int(input())
b = int(input())
for i in range(a, b + 1, 1):
  if(str(i) == str(i)[::-1]):
    print(i)